image: unitedclassifiedsapps/gitlab-ci-android-fastlane

cache:
  paths:
    - .m2/
    - .gradle/

variables:
  ANDROID_COMPILE_SDK: "31"
  ANDROID_BUILD_TOOLS: "31.0.3"
  ANDROID_SDK_TOOLS: "7562133"
  ANDROID_GRADLE_VERSION: "gradle-7.2"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - wget --quiet --output-document=gradle.zip https://services.gradle.org/distributions/${ANDROID_GRADLE_VERSION}-bin.zip
  - unzip -q gradle.zip
  - chmod +x ./gradlew
    # use yes to accept all licenses
  - yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses || true

stages:
  - build
  - test

unitTests:
  stage: test
  script:
    - ./gradlew test

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/
